# Training settings
training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 1.0e-4
  min_lr: 1.0e-6
  warmup_epochs: 5
  num_workers: 4
  early_stopping: true
  patience: 10

# Model architecture
model:
  d_model: 512
  nhead: 8
  num_layers: 8
  motion_dim: 256
  audio_dim: 128

# Diffusion settings
diffusion:
  num_steps: 50
  beta_start: 1.0e-4
  beta_end: 0.02

# Generation settings
generation:
  sequence_length: 25
  overlap: 5
  smoothing_window: 5
  generation_interval: 100

# CFG (Classifier-Free Guidance) settings
cfg:
  audio_scale: 0.5
  gaze_scale: 1.0

# Loss weights
loss:
  lambda_recon: 1.0
  lambda_identity: 0.1
  lambda_dpe: 0.1
  lambda_pose: 1.0
  lambda_expr: 1.0
  lambda_cfg: 0.1

# Data settings
data:
  frame_size: [512, 512]
  apply_post_processing: true