data:
  train_width: 512 
  train_height: 512 
  sample_rate: 25 
  n_sample_frames: 1
  n_motion_frames: 2
training:
  project_name: "vasa-training"
  gradient_accumulation_steps: 1
  frame_offset: 20
  checkpoint_path: './checkpoint_epoch100.pth'
  save_interval: 50
  log_interval: 100
  lambda_perceptual: 1.0
  lambda_adversarial: 1.0
  lambda_cosine: 1.0
  lambda_keypoints: 1.0
  lambda_gaze: 1.0
  lambda_supervised: 1.0
  lambda_unsupervised: 1.0
  batch_size: 24
  num_workers: 0
  lr: 1.0e-5
  base_epochs: 100
  hr_epochs: 50
  student_epochs: 100
  use_gpu_video_tensor: True
  prev_frames: 2  # Add this line to specify the number of previous frames to consider
  # video_dir:  '/media/oem/12TB/Downloads/CelebV-HQ/celebvhq/35666' # point to your junk folder or 40gb - https://academictorrents.com/details/843b5adb0358124d388c4e9836654c246b988ff4
  video_dir: './junk'
  sample_rate: 25  
  n_sample_frames: 100
  json_file: './data/overfit.json'

  
  w_per: 20  # perceptual loss
  w_adv: 1   # adversarial loss
  w_fm: 40   # feature matching loss
  w_cos: 2   # cycle consistency loss
  w_pairwise: 1
  w_identity: 1
  w_cyc:  1
