wandb:
  project_name: "megaportraits"

  
data:
  train_width: 512 
  train_height: 512 
  sample_rate: 25 
  n_sample_frames: 1
  n_motion_frames: 2
  frame_size: [512, 512]
  train_data: ./junk # data/voxceleb2/train
  val_data: ./junk  #data/voxceleb2/val
  max_videos: null
  cache_audio: true
  preextract_audio: true
training:
  logging_dir: "logs"
  batch_size: 1
  num_workers: 0
  sample_interval: 100
  save_frames: True
  log_dir: './logs'
  project_name: "vasa-training"
  gradient_accumulation_steps: 1
  frame_offset: 20
  checkpoint_path: './checkpoint_epoch100.pth'
  save_interval: 500
  log_interval: 100
  lambda_perceptual: 1.0
  lambda_adversarial: 1.0
  lambda_cosine: 1.0
  lambda_keypoints: 1.0
  lambda_gaze: 1.0
  lambda_supervised: 1.0
  lambda_unsupervised: 1.0
  lr: 1.0e-5
  hr_epochs: 50
  student_epochs: 100
  use_gpu_video_tensor: True
  prev_frames: 2  # Add this line to specify the number of previous frames to consider
  video_dir:  '/media/oem/12TB/Downloads/CelebV-HQ/celebvhq/35666' # point to your junk folder or 40gb - https://academictorrents.com/details/843b5adb0358124d388c4e9836654c246b988ff4
  cache_video_dir: '/media/oem/12TB/Downloads/CelebV-HQ/celebvhq/35666/cache' 

  # video_dir: './junk'
  sample_rate: 25  
  n_sample_frames: 100
  json_file: './data/overfit.json'

  # json_file: './data/celebvhq_info.json'
  w_per: 20  # perceptual loss
  w_adv: 1   # adversarial loss
  w_fm: 40   # feature matching loss
  w_cos: 2   # cycle consistency loss
  w_pairwise: 1
  w_identity: 1
  w_cyc:  1



  num_epochs: 1000
  base_epochs: 1000
  learning_rate: 2.0e-4
  min_lr: 1.0e-6
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01
  save_frequency: 5
  checkpoint_dir: "checkpoints/stage1"